services:
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - att-network

  libsql: # database server
    image: ghcr.io/tursodatabase/libsql-server:latest
    networks:
      - att-network

  garnet: # cache server
    image: ghcr.io/microsoft/garnet:latest
    networks:
      - att-network

  fluentd: # logging agent
    image: fluent/fluentd
    networks:
      - att-network

networks:
  att-network:
    driver: bridge